AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 30

Resources:
  getTodoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/getAllTodo/
      Events:
        getAllTodoEndpoint:
          Type: Api
          Properties:
            Path: /getalltodo
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TodoTable

  createTodoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/createTodo/
      Events:
        createTodoEndpoint:
          Type: Api
          Properties:
            Path: /createtodo
            Method: POST
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TodoTable

  updateTodoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/updateTodo/
      Events:
        updateTodoEndpoint:
          Type: Api
          Properties:
            Path: /updatetodo
            Method: PATCH
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TodoTable

  deleteTodoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/deleteTodo/
      Events:
        deleteTodoEndpoint:
          Type: Api
          Properties:
            Path: /deletetodo
            Method: DELETE
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TodoTable

  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      TableName: prod-Todo

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos'
